### ISSUE TITLE
Invalid subscript SpecularColor on litMetaPass.klst: 45

### ISSUE THREAD

**Issue by luisgsoft** [Jiaquarium/unity-URP-2.5D-lit-shader#3]
Lit Shader can't compile, it shows this error on Unity 2022.3.12

![image](https://github.com/Jiaquarium/unity-URP-2.5D-lit-shader/assets/52243859/2cc39446-6413-48a6-80bb-571dd8c851b1)

**Comment by ColdThunder11** [comment]
URP's change in new Unity version break it, I make a [fork](https://github.com/ColdThunder11/unity-URP-2.5D-lit-shader) to fix in Unity 2022.3, you can try it.

**Comment by Jiaquarium** [comment]
I've addressed this with this [commit](https://github.com/Jiaquarium/unity-URP-2.5D-lit-shader/commit/b2ea199fca4e7a3e297ee74020c3a3d842d7bd66) on the production branch. I'm currently working to get the production branch merged but I need to first clean it up for general use (there's a ton of extras in there that are really only relevant for edge cases specific to my game's setup).

For now, you can comment out that line shown in the above commit. Also, on Unity 2021.3 even with that error, the project will still build fine.

**Comment by luisgsoft** [comment]
Thank you, is running.
Is there any chance that run this shader with perspective camera? I've tried, and is working at 90%. Sprites are billboard, but still overlaps with 3d geometry:
Editor camera:
![image](https://github.com/Jiaquarium/unity-URP-2.5D-lit-shader/assets/52243859/9fbd359d-4830-45a9-9e10-4ebba71597d1)
Game camera. The upper part collides with 3d geometry:
![image](https://github.com/Jiaquarium/unity-URP-2.5D-lit-shader/assets/52243859/ffa08a7f-72cb-44e8-a1f8-ff4e4a2f30ea)
If I set z position in -0.5 it runs ok.
![image](https://github.com/Jiaquarium/unity-URP-2.5D-lit-shader/assets/52243859/e2be79d9-e598-47d0-aaab-8e35887ed93a)

Regards!

**Comment by luisgsoft** [comment]
Forgot it. With sprites runs ok. THe problem is with Spine GameObjects.

Regards!

**Comment by Jiaquarium** [comment]
Closing this as this commit 444631675b84d7500dd4f892a8259c653a135b31 solves this issue.
